import {ReactNode} from 'react';

export interface FinalDataInterface {
  [x: string]: ReactNode;
  ScanCode: string;
  SendScanStatus: number;
  PackingMasterId: number;
  PackingDetailsId: number;
  AssortMasterId: number;
  AssorCartonId: number;
  ShipOutPackingMasterId: number;
  ShipOutPackingDetailsId: number;
  SendMasterId: number;
  SendChallanNo: string;
  CompanyId: number;
  Company: string;
  FloorName: string;
  BuyerId: string;
  Buyer: string;
  SeasonId: number;
  Season: string;
  Styleid: number;
  Style: string;
  PoNo: string;
  ColorId: string;
  SizeId: string;
  PcbId: number;
  PcsQty: string;
  Status: string;
  Balance: number;
  ShipDate: string;
  BuyDate?: null;
  ProtoNo: number;
  SetCode: string;
  DestinationPlace: string;
  DeliveryPlace: string;
  ItemNumber: string;
  PcsPerCarton: string;
  cbmId: number;
  cbmName: string;
  cbm: number;
  PerCartonWeight: number;
  customSl: number;
  id?: number;
  receivedmasterid?: number;
  sendingcartonid?: number;
  packingmasterid?: number;
  packingdetailsid: number;
  assortmasterid: number;
  assortcartonid: number;
  companyid: any;
  floorname: string;
  buyerid: string;
  sendmasterid: number;
  sendchallanno: string;
  seasonid: string;
  styleid: string;
  operation: string;
  pono: string;
  color: string;
  size: string;
  sendtoid: number;
  receivedcartonqty: number;
  pcbid: number;
  pcspercarton: string;
  cbmid: number;
  receivedback: number;
  storelineid: string;
  stack: string;
  tostack: string;
  location: string;
  comments: string;
  isapproved: number;
  active: number;
  ssogno: number;
  shipdate: string | null;
  pcd: null;
  buydate: any;
  protono: number | null;
  setcode: string | null;
  destinationplace: any;
  deliveryplace: null;
  itemnumber: string | null;
  percartonweight: string;
  scancode: never;
  itemstatus: any;
  shipoutpackingmasterid: number;
  shipoutpackingdetailsid: number;
  userid: number;
  adloginid: number;
  Carton: number;
}
